/* Long-Horizon Prompt Lab UI.
 * Renders window.PROMPT_LAB_DATA (from data.js, generated by scripts/build_lab.py).
 * No build step, no network: open index.html directly or via a static server.
 */
(function () {
  const DATA = window.PROMPT_LAB_DATA;
  if (!DATA) {
    document.body.innerHTML = "<p style='padding:40px;font-family:sans-serif'>Missing data.js. Run scripts/build_lab.py first.</p>";
    return;
  }

  const $ = (sel) => document.querySelector(sel);
  const el = (tag, cls, text) => {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  };
  const INSTALL_COMMAND = [
    "git clone --depth 1 https://github.com/muratcankoylan/Agent-Skills-for-Context-Engineering.git /tmp/context-engineering-skills",
    "mkdir -p .cursor/skills",
    "cp -R /tmp/context-engineering-skills/skills/long-horizon-prompting .cursor/skills/",
  ].join(" && ");

  async function copyText(text) {
    try {
      await navigator.clipboard.writeText(text);
    } catch (_) {
      const area = document.createElement("textarea");
      area.value = text;
      area.setAttribute("readonly", "");
      area.style.position = "fixed";
      area.style.opacity = "0";
      document.body.appendChild(area);
      area.select();
      document.execCommand("copy");
      area.remove();
    }
  }

  const rubricById = Object.fromEntries(DATA.rubric.map((d) => [d.id, d]));

  function badge(score) {
    if (score === "na") return { cls: "bna", label: "n/a" };
    return { cls: "b" + score, label: String(score) };
  }

  // ---- Hero ----
  $("#hero-title").textContent = DATA.meta.title;
  $("#hero-subtitle").textContent = DATA.meta.subtitle;
  $("#exemplar-chip").textContent = DATA.meta.exemplar;
  $("#agg-before").textContent = DATA.meta.aggregate.before_pct + "%";
  $("#agg-after").textContent = DATA.meta.aggregate.after_pct + "%";
  $("#agg-gain").textContent = "+" + DATA.meta.aggregate.gain_pp;
  $("#agg-pairs").textContent = DATA.meta.aggregate.pairs;
  $("#honesty-note").textContent = DATA.meta.honesty_note;
  $("#copy-install").addEventListener("click", async () => {
    await copyText(INSTALL_COMMAND);
    const status = $("#install-status");
    status.textContent = "Install command copied.";
    setTimeout(() => { status.textContent = ""; }, 1800);
  });

  // ---- Tabs ----
  const tabs = $("#tabs");
  DATA.pairs.forEach((pair, i) => {
    const t = el("button", "tab");
    t.appendChild(el("span", "tab-title", pair.title));
    t.appendChild(el("span", "tab-domain", pair.domain));
    t.dataset.id = pair.id;
    t.addEventListener("click", () => select(pair.id));
    tabs.appendChild(t);
  });

  function scoreLine(block) {
    return block.total + "/" + block.max + " \u00b7 " + block.pct + "%";
  }

  function renderPair(pair) {
    const root = el("div");

    // Head
    const head = el("div", "pair-head");
    head.appendChild(el("h2", null, pair.title));
    const meta = el("div", "pair-meta");
    [["Domain", pair.domain], ["Topology", pair.topology], ["Horizon", pair.horizon]].forEach(([k, v]) => {
      const p = el("span", "pill");
      p.innerHTML = "<b>" + k + ":</b> " + escapeHtml(v);
      meta.appendChild(p);
    });
    head.appendChild(meta);
    head.appendChild(el("p", "pair-summary", pair.summary));
    root.appendChild(head);

    // Split panels
    const split = el("div", "split");
    split.id = "pair-split";
    split.appendChild(promptPanel("before", pair));
    split.appendChild(promptPanel("after", pair));
    root.appendChild(split);

    // Scorecard
    root.appendChild(el("div", "section-title", "Structural audit"));
    root.appendChild(scorecard(pair));
    root.appendChild(legend());

    // Deltas + residual
    root.appendChild(el("div", "section-title", "Material changes"));
    const cols = el("div", "two-col");
    const ul = el("ul", "deltas");
    pair.deltas.forEach((d) => {
      const li = el("li");
      li.appendChild(el("div", "delta-dim", d.dim));
      li.appendChild(el("div", "delta-text", d.text));
      ul.appendChild(li);
    });
    cols.appendChild(ul);
    const res = el("div", "residual");
    res.appendChild(el("h4", null, "Residual risk the brief cannot remove"));
    res.appendChild(el("p", null, pair.residual));
    cols.appendChild(res);
    root.appendChild(cols);

    return root;
  }

  // Soft-wrap in the source files is for editing, not layout. Collapse those
  // mid-paragraph newlines so the screenshot panes fill their column width.
  function normalizePromptDisplay(text) {
    const lines = String(text).replace(/\r\n/g, "\n").split("\n");
    const out = [];
    let paragraph = [];

    const flush = () => {
      if (!paragraph.length) return;
      out.push(paragraph.join(" ").replace(/ +/g, " ").trim());
      paragraph = [];
    };

    for (const raw of lines) {
      const trimmed = raw.trim();
      if (!trimmed) {
        flush();
        if (out.length && out[out.length - 1] !== "") out.push("");
        continue;
      }

      const isList = /^([-*]|\d+\.)\s+/.test(trimmed);
      const isHeader = /^[A-Z][A-Z0-9 /&().-]{2,}$/.test(trimmed) && trimmed.length <= 64;
      const isFormula = /^(cost\(|E_r\[|mean\(|    )/.test(raw) || /^[ ]{2,}cost\(|^[ ]{2,}E_r\[/.test(raw);

      if (isList || isHeader || isFormula) {
        flush();
        out.push(trimmed);
        continue;
      }

      paragraph.push(trimmed);
    }

    flush();
    return out.join("\n").replace(/\n{3,}/g, "\n\n").trim();
  }

  function promptPanel(kind, pair) {
    const isBefore = kind === "before";
    const panel = el("div", "panel panel-" + kind);
    const h = el("div", "panel-head");
    h.appendChild(el("span", "panel-tag", isBefore ? "01 / Original prompt" : "02 / Optimized prompt"));
    const block = pair.score_summary[kind];
    const tools = el("div", "panel-tools");
    const words = pair[kind].trim().split(/\s+/).length;
    tools.appendChild(el("span", "word-count", words + " words"));
    tools.appendChild(el("span", "panel-score", scoreLine(block)));
    const copy = el("button", "copy-button", "Copy");
    copy.type = "button";
    copy.addEventListener("click", async () => {
      await copyText(pair[kind]);
      copy.textContent = "Copied";
      setTimeout(() => { copy.textContent = "Copy"; }, 1200);
    });
    tools.appendChild(copy);
    h.appendChild(tools);
    panel.appendChild(h);

    panel.appendChild(el("div", "panel-caption",
      isBefore ? "Original launch prompt" : "Ready to paste into a long-running agent"));

    if (isBefore) {
      const tech = el("div", "techniques");
      pair.before_techniques.forEach((t) => tech.appendChild(el("span", "technique", t)));
      panel.appendChild(tech);
    } else {
      const tech = el("div", "techniques");
      ["exact success predicate", "named non-solutions", "evidence contract",
       "adversarial verification", "return gate", "harness boundaries"].forEach((t) =>
        tech.appendChild(el("span", "technique", t)));
      panel.appendChild(tech);
    }

    panel.appendChild(el("pre", "prompt", normalizePromptDisplay(pair[kind])));
    return panel;
  }

  function scorecard(pair) {
    const table = el("table", "scorecard");
    table.id = "scorecard";
    const thead = el("thead");
    const hr = el("tr");
    ["Rubric dimension (2 = adversary-proof)", "Before", "After"].forEach((h, i) => {
      const th = el("th", i === 0 ? "" : "cell-score", h);
      hr.appendChild(th);
    });
    thead.appendChild(hr);
    table.appendChild(thead);

    const tbody = el("tbody");
    DATA.rubric.forEach((dim) => {
      const tr = el("tr");
      const nameTd = el("td");
      nameTd.appendChild(el("div", "dim-name", dim.name));
      nameTd.appendChild(el("div", "dim-two", dim.two));
      tr.appendChild(nameTd);
      ["before", "after"].forEach((k) => {
        const td = el("td", "cell-score");
        const b = badge(pair.scores[k][dim.id]);
        const span = el("span", "badge " + b.cls, b.label);
        td.appendChild(span);
        tr.appendChild(td);
      });
      tbody.appendChild(tr);
    });

    const totalTr = el("tr", "score-total");
    totalTr.appendChild(el("td", null, "Total (applicable dimensions)"));
    ["before", "after"].forEach((k) => {
      totalTr.appendChild(el("td", "cell-score", scoreLine(pair.score_summary[k])));
    });
    tbody.appendChild(totalTr);
    table.appendChild(tbody);
    return table;
  }

  function legend() {
    const l = el("div", "legend");
    const items = [
      ["b2", "2 - adversary-proof"],
      ["b1", "1 - present but gameable"],
      ["b0", "0 - absent"],
      ["bna", "n/a - not applicable (e.g. single-agent run)"],
    ];
    items.forEach(([cls, label]) => {
      const s = el("span");
      const dot = el("span", "dot " + cls);
      s.appendChild(dot);
      s.appendChild(document.createTextNode(label));
      l.appendChild(s);
    });
    return l;
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  }

  function select(id) {
    const pair = DATA.pairs.find((p) => p.id === id) || DATA.pairs[0];
    document.querySelectorAll(".tab").forEach((t) => t.classList.toggle("active", t.dataset.id === pair.id));
    const main = $("#pair");
    main.innerHTML = "";
    main.appendChild(renderPair(pair));
    if (history.replaceState) history.replaceState(null, "", "#" + pair.id);
  }

  function currentId() {
    const h = (location.hash || "").replace("#", "");
    return DATA.pairs.some((p) => p.id === h) ? h : DATA.pairs[0].id;
  }

  window.addEventListener("hashchange", () => select(currentId()));
  select(currentId());
})();
